---
keys: 
  # Spring.NET : 配置文件
  SpringObjectFile: assembly://X3Platform.Location.IPQuery/X3Platform.Location.IPQuery/defaults.Objects.xml
  # IBatis : 配置映射文件
  IBatisMapping: embedded:X3Platform.Location.IPQuery.defaults.IBatis.SqlMap.xml,X3Platform.Location.IPQuery
...