---
keys: 
  # Spring.NET : 配置文件
  SpringObjectFile: assembly://X3Platform.Connect/X3Platform.Connect/defaults.Objects.xml
  # IBatis : 配置映射文件
  IBatisMapping: embedded:defaults.IBatis.SqlMap.xml,X3Platform.Connect
  # API主机名
  ApiHostName: "${HostName}"  
  # 会话定时器执行时间间隔(单位:分钟)
  SessionTimerInterval : 15
  # 会话时间限制 (单位:秒)
  SessionTimeLimit: 86400
  # 跟踪调用信息 : On | Off(默认)
  TrackingCall: Off
  # 消息队列模式: 可选的值 1.On 2.Off(默认)
  MessageQueueMode: Off
...