---
keys: 
  # Spring.NET : 配置文件
  SpringObjectFile: assembly://X3Platform.Abstractions/X3Platform.Security.Authority/defaults.Objects.xml
  # IBatis : 配置映射文件
  IBatisMapping: embedded:X3Platform.Security.Authority.defaults.IBatis.SqlMap.xml
...