---
keys: 
  # Spring.NET : 配置文件
  SpringObjectFile: assembly://X3Platform.Entities/X3Platform.Entities/defaults.Objects.xml
  # IBatis : 配置映射文件
  IBatisMapping: embedded:X3Platform.Entities.defaults.IBatis.SqlMap.xml,X3Platform.Entities
...