---
keys: 
  # Spring.NET : 配置文件
  SpringObjectFile: assembly://X3Platform.Membership.HumanResources/X3Platform.Membership.HumanResources/defaults.Objects.xml
  # IBatis : 配置映射文件
  IBatisMapping: embedded:X3Platform.Membership.HumanResources.defaults.IBatis.SqlMap.xml,X3Platform.Membership.HumanResources
...