---
keys: 
  # Spring.NET : 配置文件
  SpringObjectFile: assembly://X3Platform.Sessions/X3Platform.Sessions/defaults.Objects.xml
  # IBatis : 配置映射文件
  IBatisMapping: embedded:X3Platform.Sessions.defaults.IBatis.SqlMap.xml,X3Platform.Sessions
  # Storages : 数据存储架构标识
  StorageSchemaId: 01-14-Sessions
  # 会话持久化 : 可选的值 1.On 2.Off(默认)
  SessionPersistentMode : Off
  # 会话定时器执行时间间隔(单位:分钟)
  SessionTimerInterval : 15
  # 会话时间限制(单位:分钟)
  SessionTimeLimit : 3600
...